# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'ParkFinder' do

  pod 'GooglePlaces', '2.2.0'
  pod 'GoogleMaps', '2.2.0'
  pod 'GooglePlacePicker', '2.2.0'

end


# target 'ParkFinder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParkFinder

  # target 'ParkFinder-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

#   target 'ParkFinderTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end

target 'ParkFinder-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ParkFinder-tvOS

  target 'ParkFinder-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
